# Generated by Django 5.2.5 on 2025-08-23 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_between',
            field=models.ManyToManyField(blank=True, related_name='shared_expenses', to='expenses.participant'),
        ),
    ]
