# Generated by Django 5.2.5 on 2025-08-27 09:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_category_expense_category_settlement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='settlement',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_at'], name='expenses_ev_created_2e81f1_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['event'], name='expenses_ex_event_i_8f450f_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-created_at'], name='expenses_ex_created_be0371_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['event'], name='expenses_pa_event_i_888629_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['event'], name='expenses_se_event_i_e37c60_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['-created_at'], name='expenses_se_created_554eca_idx'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='participant',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_participant_name_per_event'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='settlement_amount_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='settlement',
            constraint=models.CheckConstraint(condition=models.Q(('from_participant', models.F('to_participant')), _negated=True), name='settlement_from_not_to'),
        ),
    ]
